#!/bin/bash
#BSUB -J "Trim_n_Error_corr"                                      
#BSUB -R "rusage[mem=312]"    
#BSUB -R "rusage[scratch=10000]"         
#BSUB -n 1                                            
#BSUB -W 20:00                             
#BSUB -oo ~/output_files

module load bbmap/37.36 
module load spades

#[1] define variables
#[1.1] project variable
PROJECT="Dual_metaT"
#[1.2] folder variable
DATA_FOLDER= ~/data

#note:
#DATA_FOLDER is an absolute path, with fastq reads being in a subfolder called "00_reads".
#(reads have been previously extracted by tar -xzf raw.tar.gz -C 00_reads) Where -x:extract files; -f:tar archive name; -z:work on .tar.gz file format; -C:set dir name to extract files

#[2]create output folders
cd $TMPDIR
mkdir trimmed_reads
mkdir spades
mkdir $DATA_FOLDER/01_corr_reads

#[3]copy files into $TMPDIR for faster processing
#[3.1] the raw reads
scp $DATA_FOLDER/00_reads/raw/*.fastq.gz ./
#[3.2] the adaptors
scp $DATA_FOLDER/Illumina_adapters.fasta ./

##[4] create a sample list---------------------------------------
##[do only once] Rename filenames to have more simple ones (this will depend on how samples are named)
#cd $READS_FOLDER
#for filename in *fastq.gz; do 
#    [ -f "$filename" ] || continue
#    mv "$filename" "${filename//20220215.B-o27409_1_/}"
#done
##[do only once] Create a sample list
#ls *R1.fastq.gz | sed 's/_R1.fastq.gz//g' > $DATA_FOLDER/Sample_list.txt
#-----------------------------------------

#[5] Adapter and quality trimming
for i in $(cat Sample_list.txt);
#running bbduk. 
do
    bbduk.sh \
        threads=32 \
        ktrim=r \
        minlength=100 \
        ref=Illumina_adapters.fasta \
        in=reads/"$i"_R1.fastq.gz\
        in2=reads/"$i"_R2.fastq.gz\
        out1=trimmed_reads/"$i"_bbduk_R1.fastq \
        out2=trimmed_reads/"$i"_bbduk_R2.fastq

#running SPAdes error-correction
    spades.py \
        --meta \
        --only-error-correction \
        -t 32 -m 512 \
        --tmp-dir $TMPDIR/username \
        -1 trimmed_reads/"$i"_bbduk_R1.fastq \
        -2 trimmed_reads/"$i"_bbduk_R2.fastq \
        -o reads_corrected_"$i"

#moving and reanaming corrected reads generated by SPAdes. 
mv reads_corrected_"$i"/corrected/"$i"_bbduk_R1.00.0_0.cor.fastq.gz spades/"$i"_corr.read1.fastq.gz
mv reads_corrected_"$i"/corrected/"$i"_bbduk_R1.00.0_0.cor.fastq.gz spades/"$i"_corr.read1.fastq.gz;
done

scp -r trimmed_reads/ $DATA_FOLDER/01_corr_reads/bbduk_trimmed
scp -r spades/ $DATA_FOLDER/01_corr_reads/spades_corrected





